export { default as Home } from "./Home";
export { default as Products } from "./Products";
export { default as Categories } from "./Categories";
export { default as AboutUs } from "./AboutUs";
export { default as Login } from "./Login";
export { default as Register } from "./Register";
export { default as Error } from "./Error";
export { default as Cart } from "./Cart";
export { default as Wishlist } from "./Wishlist";
